# Generated by Django 4.1 on 2023-02-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_blog_audience_blog_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topic',
            new_name='blogIdea',
        ),
    ]
