# Generated by Django 4.1 on 2023-02-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_topic_blog_blogidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='wordCount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
