# Generated by Django 4.1 on 2023-03-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
