# Generated by Django 3.2.18 on 2023-06-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_settings_client_clientlogo_client_taxnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('Kotli', 'Kotli'), ('Mirpur', 'Mirpur'), ('Nakyal', 'Nakyal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('Rs', 'PKR'), ('$', 'USD')], default='R', max_length=100),
        ),
    ]
